parameters:
#    locksso_matic_sword.example.class: LOCKSSOMatic\SWORDBundle\Example

services:
    kernel.listener.sword_exception_listener:
        class: LOCKSSOMatic\SWORDBundle\EventListener\SWORDEventListener
        arguments: [@templating, @logger]
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException} 
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController} 
            