LOCKSSOMatic\CRUDBundle\Entity\Aus:
    type: entity
    oneToMany:
        content:
            targetEntity: Content
            mappedBy: au
        auStatus:
            targetEntity: AuStatus
            mappedBy: au
        auProperties:
            targetEntity: AuProperties
            mappedBy: au
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: aus
            joinColumn:
                name: plns_id
                referencedColumnName: id
        plugin:
            targetEntity: Plugins
            inversedBy: aus
            joinColumn:
                name: plugins_id
                referencedColumnName: id
        contentProvider:
            targetEntity: ContentProviders
            inversedBy: aus
            joinColumn:
                name: contentproviders_id
                referencedColumnName: id
    table: aus
    indexes:
        plns_id_idx:
            columns:
                - plns_id
        plugins_id_idx:
            columns:
                - plugins_id                
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        managed:
            type: boolean
            nullable: false
            default: true
            comment: 'Should LOCKSSOMatic manage this PLN.'
        auid:            
            type: string
            length: 255
            nullable: true
            comment: 'The LOCKSS auId. @todo: Explain where this is generated.'
        manifestUrl:
            type: string
            length: 512
            nullable: true
            comment: 'The LOCKSS manifest URL for the AU.'
            column: manifest_url
        comment:
            type: string
            length: 512
            nullable: true
            comment: 'A LOCKSSOMatic comment on the AU.'
            column: comment
    lifecycleCallbacks: {  }
