LOCKSSOMatic\CRUDBundle\Entity\Aus:
    type: entity
    oneToMany:
        content:
            targetEntity: Content
            mappedBy: au
        auStatus:
            targetEntity: AuStatus
            mappedBy: au
        auProperties:
            targetEntity: AuProperties
            mappedBy: au
        pluginProperties:
            targetEntity: PluginProperties
            mappedBy: au
    table: aus
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plns table.'
            column: plns_id
        externalTitleDbsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the external_title_dbs table.'
            column: external_title_dbs_id            
        auid:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The LOCKSS auId. @todo: Explain where this is generated.'
        manifestUrl:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The LOCKSS manifest URL for the AU.'
            column: manifest_url
    lifecycleCallbacks: {  }
