LOCKSSOMatic\CRUDBundle\Entity\AuStatus:
    type: entity
    manyToOne:
        au:
            targetEntity: Aus
            inversedBy: auStatus
            joinColumn:
                name: aus_id
                referencedColumnName: id
    table: au_status
    indexes:
        aus_id_idx:
            columns:
                - aus_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ausId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the aus table.'
            column: aus_id
        boxHostname:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The hostname of the box that perserves the AU.'
            column: box_hostname
        queryDate:
            type: datetime
            nullable: true
            comment: 'Timestamp indicating when the box was queried.'
            column: query_date
        propertyKey:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'AU property key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'AU property value.'
            column: property_value
    lifecycleCallbacks:
            prePersist: [setQueryDate]
