LOCKSSOMatic\CRUDBundle\Entity\Content:
    type: entity
    table: content
    indexes:
        content_providers_id_idx:
            columns:
                - content_providers_id
        deposits_id_idx:
            columns:
                - deposits_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contentProvidersId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: content_providers_id
        depositsId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: deposits_id
        ausId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: aus_id
        url:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        title:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        size:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        dateAddedToAu:
            type: datetime
            nullable: true
            comment: ''
            column: date_added_to_au
        checksumType:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: checksum_type
        checksumValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: checksum_value
    lifecycleCallbacks: {  }
