LOCKSSOMatic\CRUDBundle\Entity\ContentOwners:
    type: entity
    oneToMany:
        contentProviders:
            targetEntity: ContentProviders
            mappedBy: contentOwner
    table: content_owners
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Name of the insitution, department, or individual who is responsible for content.'
        emailAddress:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'One or more email addresses used in sending reports, alerts, etc.'
            column: email_address
    lifecycleCallbacks: {  }
