LOCKSSOMatic\CRUDBundle\Entity\ContentProviders:
    type: entity
    manyToOne:
        contentOwner:
            targetEntity: ContentOwners
            inversedBy: contentProviders
            joinColumn:
                name: content_owners_id
                referencedColumnName: id
        pln:
            targetEntity: Plns
            inversedBy: contentProviders
            joinColumn:
                name: plns_id
                referencedColumnName: id
        plugin:
            targetEntity: Plugins
            inversedBy: contentProviders
            joinColumn:
                name: plugins_id
                referencedColumnName: id
    oneToMany:
        deposits:
            targetEntity: Deposits
            mappedBy: contentProvider
        aus:
            targetEntity: Aus
            mappedBy: contentProvider
    table: content_providers
    indexes:
        content_owners_id_idx:
            columns:
                - content_owners_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            length: 24
            comment: 'Either "application" (deposits content via SWORD interface) or "manual" (deposits content via web form).'
        uuid:
            type: string
            length: 36
            comment: 'UUID for the content provider.'
            nullable: false
        permissionUrl:
            type: string
            length: 255
            comment: 'The URL for the permission file.'
            nullable: false
        name:
            type: string
            length: 255
            comment: 'The name of the content provider.'
        ipAddress:
            type: string
            length: 16
            comment: 'The IP address of the content provider application.'
            column: ip_address
        hostname:
            type: string
            length: 255
            comment: 'The hostname of the content provider application.'
        checksumType:
            type: string
            length: 24
            comment: 'A standard identifier for commonly used checksum algorithms such as md5, sha1, etc.'
            column: checksum_type
        maxFileSize:
            type: integer
            nullable: true
            unsigned: false
            comment: 'The maximum allowed size for a single file included in deposits from the content provider, in kB.'
            column: max_file_size
        maxAuSize:
            type: integer
            nullable: true
            unsigned: false
            comment: 'The maximum cumulative size for an Archival Unit containing deposits from the content provider, in kB.'
            column: max_au_size            
