LOCKSSOMatic\CRUDBundle\Entity\Deposits:
    type: entity
    manyToOne:
        contentProvider:
            targetEntity: ContentProviders
            inversedBy: deposit
            joinColumn:
                name: content_providers_id
                referencedColumnName: id    
    oneToMany:
        content:
            targetEntity: Content
            mappedBy: deposit 
    table: deposits
    indexes:
        content_providers_id_idx:
            columns:
                - content_providers_id
        uuid:
            columns:
                - uuid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: true
            length: 36
            fixed: false
            comment: 'A UUID identifying the deposit, supplied by the content provider in the <sword:id> element.'
        title:
            type: string
            length: 255
            nullable: true
            fixed: false
            comment: 'The title of the deposit.'
        dateDeposited:
            type: datetime
            nullable: true
            comment: 'Timestamp indicating when was deposit was created.'
            column: date_deposited
    lifecycleCallbacks:
        prePersist: [setDateDeposited]
