LOCKSSOMatic\CRUDBundle\Entity\PlnProperties:
    type: entity
    manyToOne:
        pln:
            targetEntity: Plns
            inversedBy: plnProperties
            joinColumn:
                name: plns_id
                referencedColumnName: id
    table: pln_properties
    indexes:
        plns_id_idx:
            columns:
                - plns_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        plnsId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Foreign key for the plns table.'
            column: plns_id
        parentId:
            type: integer
            nullable: true
            unsigned: false
            comment: 'id value from this table of the property''s parent property.'
            column: parent_id
        propertyKey:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'PLN property key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'PLN property value.'
            column: property_value
    lifecycleCallbacks: {  }
