LOCKSSOMatic\CRUDBundle\Entity\Plns:
    type: entity
    oneToMany:
        plnProperties:
            targetEntity: PlnProperties
            mappedBy: pln
        externalTitleDbs:
            targetEntity: ExternalTitleDbs
            mappedBy: pln
    table: plns
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The name of the PLN.'
        propsPath:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The URL of the lockss.xml file for the PLN.'
            column: props_path
    lifecycleCallbacks: {  }
