LOCKSSOMatic\CRUDBundle\Entity\Plns:
    type: entity
    oneToMany:
        contentProviders:
            targetEntity: ContentProviders
            mappedBy: pln
        aus:
            targetEntity: Aus
            mappedBy: pln
        plnProperties:
            targetEntity: PlnProperties
            mappedBy: pln
        externalTitleDbs:
            targetEntity: ExternalTitleDbs
            mappedBy: pln
        boxes:
            targetEntity: Boxes
            mappedBy: pln
    table: plns
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
            comment: 'The name of the PLN.'
        propsPath:
            type: text
            nullable: true
            length: null
            comment: 'The URL of the lockss.xml file for the PLN.'
            column: props_path
