LOCKSSOMatic\CRUDBundle\Entity\Plugins:
    type: entity
    oneToMany:
        pluginProperties:
            targetEntity: PluginProperties
            mappedBy: plugin
        aus:
            targetEntity: Aus
            mappedBy: plugin            
    table: plugins
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'The name of the plugin.'
    lifecycleCallbacks: {  }
