LOCKSSOMatic\CRUDBundle\Entity\PluginProperties:
    type: entity
    manyToOne:
        plugin:
            targetEntity: Plugins
            inversedBy: pluginProperties
            joinColumn:
                name: plugins_id
                referencedColumnName: id
        parent:
            targetEntity: PluginProperties
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
    oneToMany:
        children:
            targetEntity: PluginProperties
            mappedBy: parent
    table: plugin_properties
    indexes:
        plugins_id_idx:
            columns:
                - plugins_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Primary key for this table.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        propertyKey:
            type: string
            length: 255
            nullable: false
            comment: 'Plugin proprety key.'
            column: property_key
        propertyValue:
            type: text
            nullable: true
            comment: 'Plugin property value.'
            column: property_value
